In [23]:
# Import Libraries
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [40]:
# Load Dataset
dataset = pd.read_csv("youtube.csv")
print("Dataset Preview:")
print(dataset.head())

Dataset Preview:
   index     video_id trending_date  \
0      0  2kyS6SvSYSE      17.14.11   
1      1  1ZAPwfrtAFY      17.14.11   
2      2  5qpjK5DgCt4      17.14.11   
3      3  puqaWrEC7tY      17.14.11   
4      4  d380meD0W0M      17.14.11   

                                               title          channel_title  \
0                 WE WANT TO TALK ABOUT OUR MARRIAGE           CaseyNeistat   
1  The Trump Presidency: Last Week Tonight with J...        LastWeekTonight   
2  Racist Superman | Rudy Mancuso, King Bach & Le...           Rudy Mancuso   
3                   Nickelback Lyrics: Real or Fake?  Good Mythical Morning   
4                           I Dare You: GOING BALD!?               nigahiga   

   category_id publish_date      time_frame published_day_of_week  \
0           22   13/11/2017  17:00 to 17:59                Monday   
1           24   13/11/2017    7:00 to 7:59                Monday   
2           23   12/11/2017  19:00 to 19:59                Sunday 

In [42]:
dataset['target'] = np.where(dataset['views'] > dataset['views'].median(), 1, 0)
X = dataset[['likes','dislikes','comment_count','category_id']].values
Y = dataset['target'].values
print("\nX Sample:\n", X[:5])
print("\nY Sample:\n", Y[:5]) 


X Sample:
 [[ 57527   2966  15954     22]
 [ 97185   6146  12703     24]
 [146033   5339   8181     23]
 [ 10172    666   2146     24]
 [132235   1989  17518     24]]

Y Sample:
 [1 1 1 0 1]


In [45]:
print("\nMissing Values:\n")
print(dataset.isnull().sum())


Missing Values:

index                     0
video_id                  0
trending_date             0
title                     0
channel_title             0
category_id               0
publish_date              0
time_frame                0
published_day_of_week     0
publish_country           0
tags                      0
views                     0
likes                     0
dislikes                  0
comment_count             0
comments_disabled         0
ratings_disabled          0
video_error_or_removed    0
target                    0
dtype: int64


In [46]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
X = imputer.fit_transform(X)
print("\nAfter Imputation (First 5 rows):\n", X[:5])


After Imputation (First 5 rows):
 [[5.75270e+04 2.96600e+03 1.59540e+04 2.20000e+01]
 [9.71850e+04 6.14600e+03 1.27030e+04 2.40000e+01]
 [1.46033e+05 5.33900e+03 8.18100e+03 2.30000e+01]
 [1.01720e+04 6.66000e+02 2.14600e+03 2.40000e+01]
 [1.32235e+05 1.98900e+03 1.75180e+04 2.40000e+01]]


In [47]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 3] = labelencoder_X.fit_transform(X[:, 3])
print("\nAfter Label Encoding:\n", X[:5])


After Label Encoding:
 [[5.75270e+04 2.96600e+03 1.59540e+04 7.00000e+00]
 [9.71850e+04 6.14600e+03 1.27030e+04 9.00000e+00]
 [1.46033e+05 5.33900e+03 8.18100e+03 8.00000e+00]
 [1.01720e+04 6.66000e+02 2.14600e+03 9.00000e+00]
 [1.32235e+05 1.98900e+03 1.75180e+04 9.00000e+00]]


In [48]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(
    transformers=[("encoder", OneHotEncoder(), [3])],
    remainder='passthrough'
)
X = ct.fit_transform(X)
print("\nAfter One Hot Encoding:")
print("Shape:", X.shape)


After One Hot Encoding:
Shape: (161470, 21)


In [49]:
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)
print("\nEncoded Y Sample:\n", Y[:5])


Encoded Y Sample:
 [1 1 1 0 1]


In [50]:

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=0
)
print("\nTraining Shape:", X_train.shape)
print("Testing Shape:", X_test.shape)


Training Shape: (129176, 21)
Testing Shape: (32294, 21)


In [51]:
X_train = X_train.toarray()
X_test = X_test.toarray()
print("\nConverted to Dense Matrix")
print("X_train Shape:", X_train.shape)


Converted to Dense Matrix
X_train Shape: (129176, 21)


In [52]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
print("\nAfter Scaling (First 5 rows):\n", X_train[:5])


After Scaling (First 5 rows):
 [[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 2.08609920e-03 2.98204960e-04
  6.17275981e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 1.26738854e-02 3.49928097e-03
  5.12757139e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 1.63202393e-02 2.45710604e-03
  